USE [master]
GO
/****** Object:  Database [BookOfRecipes]    Script Date: 25.09.2020 22:36:11 ******/
CREATE DATABASE [BookOfRecipes]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BookOfRecipes', FILENAME = N'C:\Users\8570W\BookOfRecipes.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BookOfRecipes_log', FILENAME = N'C:\Users\8570W\BookOfRecipes_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [BookOfRecipes] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BookOfRecipes].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BookOfRecipes] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BookOfRecipes] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BookOfRecipes] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BookOfRecipes] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BookOfRecipes] SET ARITHABORT OFF 
GO
ALTER DATABASE [BookOfRecipes] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BookOfRecipes] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BookOfRecipes] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BookOfRecipes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BookOfRecipes] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BookOfRecipes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BookOfRecipes] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BookOfRecipes] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BookOfRecipes] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BookOfRecipes] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BookOfRecipes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BookOfRecipes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BookOfRecipes] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BookOfRecipes] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BookOfRecipes] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BookOfRecipes] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BookOfRecipes] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BookOfRecipes] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BookOfRecipes] SET  MULTI_USER 
GO
ALTER DATABASE [BookOfRecipes] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BookOfRecipes] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BookOfRecipes] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BookOfRecipes] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BookOfRecipes] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BookOfRecipes] SET QUERY_STORE = OFF
GO
USE [BookOfRecipes]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [BookOfRecipes]
GO
USE [master]
GO
ALTER DATABASE [BookOfRecipes] SET  READ_WRITE 
GO